[2025-04-17T21:32:04.293+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-17T21:32:04.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_demo.validate_data manual__2025-04-17T21:32:00.699900+00:00 [queued]>
[2025-04-17T21:32:04.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_demo.validate_data manual__2025-04-17T21:32:00.699900+00:00 [queued]>
[2025-04-17T21:32:04.385+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-17T21:32:04.471+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_data> on 2025-04-17 21:32:00.699900+00:00
[2025-04-17T21:32:04.476+0000] {standard_task_runner.py:63} INFO - Started process 936 to run task
[2025-04-17T21:32:04.480+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_demo', 'validate_data', 'manual__2025-04-17T21:32:00.699900+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmppeoydz7x']
[2025-04-17T21:32:04.483+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask validate_data
[2025-04-17T21:32:04.511+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-17T21:32:04.552+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_demo.validate_data manual__2025-04-17T21:32:00.699900+00:00 [running]> on host b3f0d5cbc6df
[2025-04-17T21:32:04.703+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_demo' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T21:32:00.699900+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T21:32:00.699900+00:00'
[2025-04-17T21:32:04.707+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-17T21:32:04.771+0000] {logging_mixin.py:188} INFO - 1599 rows loaded.
[2025-04-17T21:32:04.773+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-17T21:32:04.776+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-17T21:32:04.797+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_demo, task_id=validate_data, run_id=manual__2025-04-17T21:32:00.699900+00:00, execution_date=20250417T213200, start_date=20250417T213204, end_date=20250417T213204
[2025-04-17T21:32:04.934+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-17T21:32:04.975+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-04-17T21:32:04.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
