[2025-05-01T21:14:16.826+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-01T21:14:16.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_demo.validate_data manual__2025-05-01T21:14:08.265416+00:00 [queued]>
[2025-05-01T21:14:16.867+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_demo.validate_data manual__2025-05-01T21:14:08.265416+00:00 [queued]>
[2025-05-01T21:14:16.868+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-01T21:14:16.889+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_data> on 2025-05-01 21:14:08.265416+00:00
[2025-05-01T21:14:16.894+0000] {standard_task_runner.py:63} INFO - Started process 360 to run task
[2025-05-01T21:14:16.900+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_demo', 'validate_data', 'manual__2025-05-01T21:14:08.265416+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp1iz43ceg']
[2025-05-01T21:14:16.904+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask validate_data
[2025-05-01T21:14:16.955+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-01T21:14:17.000+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_demo.validate_data manual__2025-05-01T21:14:08.265416+00:00 [running]> on host b3f0d5cbc6df
[2025-05-01T21:14:17.151+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_demo' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T21:14:08.265416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T21:14:08.265416+00:00'
[2025-05-01T21:14:17.153+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-01T21:14:17.207+0000] {logging_mixin.py:188} INFO - 1599 rows loaded.
[2025-05-01T21:14:17.208+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-01T21:14:17.209+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-01T21:14:17.219+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_demo, task_id=validate_data, run_id=manual__2025-05-01T21:14:08.265416+00:00, execution_date=20250501T211408, start_date=20250501T211416, end_date=20250501T211417
[2025-05-01T21:14:17.276+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-01T21:14:17.307+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-05-01T21:14:17.329+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
