[2025-05-02T02:22:30.829+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-02T02:22:30.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_demo.validate_data manual__2025-05-02T02:22:25.123693+00:00 [queued]>
[2025-05-02T02:22:30.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_demo.validate_data manual__2025-05-02T02:22:25.123693+00:00 [queued]>
[2025-05-02T02:22:30.991+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-02T02:22:31.073+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_data> on 2025-05-02 02:22:25.123693+00:00
[2025-05-02T02:22:31.081+0000] {standard_task_runner.py:63} INFO - Started process 2593 to run task
[2025-05-02T02:22:31.087+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_demo', 'validate_data', 'manual__2025-05-02T02:22:25.123693+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp08m9xqr3']
[2025-05-02T02:22:31.091+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask validate_data
[2025-05-02T02:22:31.128+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-02T02:22:31.193+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_demo.validate_data manual__2025-05-02T02:22:25.123693+00:00 [running]> on host b3f0d5cbc6df
[2025-05-02T02:22:31.353+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_demo' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T02:22:25.123693+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T02:22:25.123693+00:00'
[2025-05-02T02:22:31.355+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-02T02:22:31.425+0000] {logging_mixin.py:188} INFO - 1599 rows loaded.
[2025-05-02T02:22:31.426+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-02T02:22:31.428+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-02T02:22:31.481+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_demo, task_id=validate_data, run_id=manual__2025-05-02T02:22:25.123693+00:00, execution_date=20250502T022225, start_date=20250502T022230, end_date=20250502T022231
[2025-05-02T02:22:31.548+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-02T02:22:31.639+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-05-02T02:22:31.669+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
